spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  data:
    redis:
      host: localhost
      port: "6379"

  jwt:
    secret: ZGF5b25lLXNwcmluZ2Jvb3QtY2xhc3Mtc3R1ZHk=



scheduler:
  scrap:
    yahoo: "0 0 0 * * *"


